services:
  - type: web
    name: ng-dhis2-malaria-dashboard
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    autoDeploy: true
    envVars:
      - key: DHIS2_BASE
        value: https://dhis2nigeria.org.ng/dhis
      - key: DHIS2_TIMEOUT
        value: "30"
      - key: DHIS2_USER
        sync: false
      - key: DHIS2_PASS
        sync: false
